Login
Fisiomfulness/fisiomfulness pull request #74
Opened 2024-01-25 21:27 UTC by molinito

Se añadió el componente Login, y un componente Group que contiene logo y lema de la empresa, de acuerdo al diseño de Figma. Se agregó botón de login al navbar para tener acceso desde la pantalla del home.  El diseño esta hecho responsivo, pero queda por definir el diseño definitivo que se le dará en pantalla chica, por lo pronto, la imagen, el formulario y campos de éste se adaptan a pantalla chica.

2024-01-25 23:56 UTC, TM10YMhp requested changes

2024-01-25 23:56 UTC, TM10YMhp commented on src/app/globals.css
> +}
no encuentro una utilidad para agregarlo en este PR, quizas se deba restaurar este archivo.

2024-01-25 23:56 UTC, TM10YMhp commented on src/app/layout.js
> +import { metadata } from "./metadata";
```suggestion
```

`metadata` deja de funcionar si se usa `"use client"`, se deberia elimina esta linea y el archivo `metadata.js`.

2024-01-25 23:56 UTC, TM10YMhp commented on src/app/metadata.js
> +  };
este archivo no seria necesario.

2024-01-26 01:17 UTC, molinito commented on src/app/layout.js
> +import { metadata } from "./metadata";
Ale... Es correcto el comentario. El repo original que bajé contenía un export const metada en el layout.js, que es el que llevé a un archivo separado metada.js para que renderizara bien el componente. Ya con el 'use client" no es necesario. Aprecio mucho la corrección.

2024-01-26 01:18 UTC, molinito commented on src/app/metadata.js
> +  };
Comentado anteriormente. Procedo a eliminar ese archivo.

2024-01-26 01:33 UTC, molinito commented on src/app/globals.css
> +}
Todavía no estoy 100% familiarizado con tailwind, no recuerdo haber agregado estas lineas de comando. ¿es probable que al haber personalizado algunos estilos con css puro se hayan agregado solo...? No estoy seguro, sigo estudiando tailwind. Restauré el archivo tal cual estaba al momento de bajar el repo. Gracias x el comentario.

2024-01-26 01:42 UTC, TM10YMhp approved these changes

2024-01-26 01:42 UTC, merged